### ISSUE TITLE
error[E0554]: `#![feature]` may not be used on the stable release channel

### ISSUE THREAD

**Issue by Alexmakes** [Noeda/rllama#1]
followed guide and trying to compile get error 

```
error[E0554]: `#![feature]` may not be used on the stable release channel
 --> src/lib.rs:1:12
  |
1 | #![feature(stdsimd)]
  |            ^^^^^^^

For more information about this error, try `rustc --explain E0554`.
error: could not compile `rllama` due to previous error
```

followed the sollution from https://github.com/casbin/casbin-rs/issues/215#issuecomment-1310758095 to no affect

**Comment by Noeda** [comment]
You will need nightly Rust. I looked at the solution and the commands specified in that comment seems like that should do it.

For reference, when I type `cargo --version` and `rustc --version`, I get these:

`cargo 1.70.0-nightly (7d3033d2e 2023-03-08)`
`rustc 1.70.0-nightly (ff4b772f8 2023-03-10)`

I'll update the README.md later to explain this.
